build: format c code with clang-format
Add the make targets `lint` and `format` so developers can quickly test
their code is compliant locally. Also add check in CI to ensure repo is
always correctly formatted.

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -28,3 +28,25 @@ jobs:
 
     - name: Make C library to check that it's able to compile without warnings
       run: make -j CFLAGS="-Werror"
+
+  clang_format:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - run: |
+        DEFAULT_CLANG_VERSION=$(echo |  clang -dM -E - | grep __clang_major | awk '{print $3}')
+        CLANG_VERSION=17
+        if ((DEFAULT_CLANG_VERSION >= CLANG_VERSION)); then
+          echo "Default clang version is $DEFAULT_CLANG_VERSION, which equal or larger than wanted version $CLANG_VERSION. Aborting!"
+          exit 1
+        fi
+
+        wget https://apt.llvm.org/llvm.sh
+        chmod +x llvm.sh
+        sudo ./llvm.sh $CLANG_VERSION
+        sudo apt-get install clang-format-$CLANG_VERSION
+
+        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-$CLANG_VERSION 100
+        sudo update-alternatives --set clang-format /usr/bin/clang-format-$CLANG_VERSION
+
+    - run: make lint
